name: 0xKits
version: '${project.version}'
main: com.lairon.plugin.xkits.KitsPlugin
api-version: 1.16
authors: [ 0xLairon1 ]
description: Kit system for your server
commands:
  kit:
    aliases:
      - kits